version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: serviceone
      POSTGRES_PASSWORD: serviceone
      POSTGRES_DB: assignment
    ports:
      - "3306:5432"